spring:
  application.name: money-raven
  jpa.hibernate.ddl-auto: validate

ironbank:
  те-кто-возвращают-долги:
    - Ланистеры

ворон:
  куда-лететь: браавос, главный банк
  вкл: true


server:
  ssl:
    enabled: false